### ISSUE TITLE
Missing menus and incorrect page numbers with Simple Isotope

### ISSUE THREAD

**Issue by Brenyco** [conseilgouz/mod_simple_isotope_j4#1]
We unfortunately have a few issues with Simple Isotope. 
Not all menus that we have entered in the categories are being displayed. Most of the time, one or more are missing. 
I have set it to display 20 posts per page, but it shows fewer (varying amounts). 
When I use page numbers and only have 2 posts in a category, it shows 3 pages on the website. 
On the first page, it shows the first post, on the second page it removes the menu item and shows nothing, and when I click on page 3, 
it shows the menu item and the second post. 
Is this an error on our part, or is it due to Simple Isotope? 

You can see it clearly here: 

https://soatnk.chance-berlin.com/index.php/angebote-nach-kategorien/hilfe-in-krisensituationen

under the menu item 'Aidshilfe'.

**Comment by conseilgouz** [comment]
Fix in version 4.3.19
